// import { call, select, put } from 'redux-saga/effects'
// import EtherScan from '../../Api/services/EtherScan'
// import HBScan from '../../Api/services/HBScan'
// import Ethplorer from '../../Api/services/Ethplorer'
// import CoinMarketCap from '../../Api/services/CoinMarketCap'
// import * as sagaAction from './sagaActions'
// import init from '../lib/initState'
// import { convertWeiToBalance, getDecimalNumber, formatNumber, formatNumberWithPrecision, sortArray, jsonToMap, convertTimestampToDate } from '@/globalFunction'
// import FiatMoneyConvert from '../../HBLibrary/FiatMoneyConvert'
// import { HBCRYPTO } from '@/globalConstants'
// import { setAccountHistory, setTokenHistory, setIsLoadAPI } from '../actions/globalActions'
// import Settings from '../../settings'
